name: anime_world
description: "Follow your favroite animes everywhere."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.6.6
  http: ^1.1.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  carousel_slider_plus: ^7.1.0
  go_router: ^14.6.2
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  launcher_name: ^1.0.2

launcher_name:
  default: "Anime World"
  fa: "دنیای انیمه"
  ch: "动漫世界"
  ja: "アニメワールド"

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - lib/src/.env